# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-01 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20160430_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trader',
            name='checkatrade_url',
            field=models.URLField(default=b'', help_text=b"Trader's location on checkatrade"),
        ),
        migrations.AlterField(
            model_name='trader',
            name='url',
            field=models.URLField(help_text=b"Trader's url"),
        ),
    ]
