# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-02 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20160501_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ref', models.CharField(default=b'checkatrade', max_length=255)),
                ('results_page', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='trader',
            options={'ordering': ['-updated']},
        ),
        migrations.AddField(
            model_name='trader',
            name='average_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trader',
            name='trader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traders', to='scraper.Scraper'),
        ),
    ]
