# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-02 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_trader_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='checkatrade_url',
            field=models.URLField(default=b'', help_text=b"Trader's location on checkatrade", max_length=355),
        ),
        migrations.AlterField(
            model_name='trader',
            name='name',
            field=models.CharField(max_length=355),
        ),
        migrations.AlterField(
            model_name='trader',
            name='page',
            field=models.TextField(default=b''),
        ),
    ]
